
/*DDL:
-CREATE TABLE DOLGOZO (KOD PRIMARY KEY, NEV VARCHAR2(30) NOT NULL, FIZETES INT, UZEM INT REFERENCES UZEMEK);
-DROP TABLE DOLGOZO;
-ALTER TABLE DOLGOZO ADD(VEGZETTSEG CHAR(20))

DML:
-INSERT INTO DOLGOZO VALUES (1, 'PETER', 200, 3);
-UPDATE DOLGOZO SET FIZETES = 3000 WHERE KOD = 3;
-DELETE FROM DOLGOZO WHERE FIZETES > 3000;

INTEGRÁLÁSI ELEMEK:
-PK
-FK
-UNIQUE
-NOT NULL
-CHECK FELT

CREATE TABLE MUSER (ID INT PRIMARY KEY,  USERNAME VARCHAR2(30) UNIQUE NOT NULL, E_MAIL VARCHAR2(30) NOT NULL, DATE_CREATED DATE NOT NULL);
CREATE TABLE POSTS(ID INT PRIMARY KEY, USER_ID REFERENCES MUSERS, P_CONTENT VARCHAR2(2000), DATE_CREATED DATE NOT NULL);
CREATE TABLE FAVOURITES ( ID INT PRIMARY KEY, USER_ID REFERENCES MUSERS, POST_ID REFERENCES POSTS);
CREATE TABLE REPLIES (ID INT PRIMARY KEY, USER_ID REFERENCES MUSERS, POST_ID REFERENCES POSTS, P_CONTENT VARCHAR2(2000), DATE_CREATED DATE NOT NULL);

INSERT INTO MUSERS VALUES(1, "Peter", bigcula@haha.com, TO.DATE('2023.07.12', 'YYYY.MM.DD'));
INSERT INTO MUSERS VALUES(2, "Paul", pali@haha.com, TO.DATE('2023.07.12', 'YYYY.MM.DD'));
INSERT INTO MUSERS VALUES(2, "Anna", annasz@haha.com, TO.DATE('2023.08.12', 'YYYY.MM.DD'));

INSERT INTO POSTS VALUES(1, 2, 'PROBA 1', SYSDATE);
INSERT INTO POSTS VALUES(2, NULL, 'PROBA 1', SYSDATE);

SELECT * FROM POSTS;

UPDATE POSTS SET USER_ID = 1 WHERE ID = 2;
*/

